import Head from 'next/head';
import Navbar from '../components/nav/navbar';
import Banner from '../components/banner/banner';
import SectionCards from '../components/card/section-cards';

import styles from '../styles/Home.module.css';

import { getPopularVideos, getVideos } from '../lib/videos';

export async function getServerSideProps() {
  const gameTrailers = await getVideos('upcoming pc games');
  const gameReviews = await getVideos('video game review');
  const twitchHighlights = await getVideos('twitch highlights');
  const gamingPopular = await getPopularVideos('Gaming popular');
  return {
    props: { gameTrailers, gameReviews, twitchHighlights, gamingPopular },
  };
}

export default function Home({
  gameTrailers,
  gameReviews,
  twitchHighlights,
  gamingPopular,
}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bing Chilling</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={styles.main}>
        <Navbar username='zsiga.michal2@gmail.com' />

        <div className={styles.bannerImg}>
          <Banner
            title='World of Warcraft: Dragonflight'
            subTitle='Upcoming expansion for one of biggest mmorpgs of all time'
            imgUrl='/static/images/image.svg'
          />
        </div>

        <div className={styles.sectionWrapper}>
          <SectionCards
            title='Upcoming games'
            videos={gameTrailers}
            size='large'
          />
          <SectionCards
            title='Game reviews'
            videos={gameReviews}
            size='small'
          />
          <SectionCards
            title='Twitch highlights'
            videos={twitchHighlights}
            size='medium'
          />
          <SectionCards
            title='Gaming popular'
            videos={gamingPopular}
            size='small'
          />
        </div>
      </div>
    </div>
  );
}
